services:
  object-extraction:
      runtime: nvidia
      shm_size: 22gb
      stdin_open: true # docker run -i
      tty: true # docker run -t
      command: /bin/bash -c "/usr/sbin/sshd -D & jupyter-lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --LabApp.token=''"
      ports:
        - $PORT:22
        - $PORT_NOTEBOOK:8888
      environment:
        - HOME=$HOME
        - USER=$USER
        - NVIDIA_VISIBLE_DEVICES=7
        - CUDA_DEVICE_ORDER=PCI_BUS_ID
      volumes:
        - /data/$USER/object-extraction:/projects/object-extraction
        - $HOME/.ssh:/root/.ssh
        - /data/$USER/eqa-test:/projects/eqa-test
      build:
        dockerfile: Dockerfile
